# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 593f20f2774118cea5ce6bb79aeb043840a17a0ee52b526e141d43d35f57bc50c6696cfc44d0d6c48859287aa68dfdef96b646a434e94c7bf0666374c55832e3

  telegram_token: '234289654:AAGLp0viS8q0OXTwcPD_NYs0MUvYwp8KK_Q'
  telegram_test_chat_id: '195081'

  twilio_sid: "AC1f9a753d8c904a37dc3bbfb75d2b735c"
  twilio_token: "462fa2c260d6fb7663a75e06e1daa250"
  twilio_phone_number: "+12054172029"

  mail_server_user_name: 'e0f3c0a17413cc'
  mail_server_password: '97f6448ef8a24b'

  facebook_app_id: '1694859610767598'
  facebook_secret_key: 'a86431a4660b427582c5ce0e119c46e7'
  facebook_access_token: 'EAAYFd0ELQO4BAEpFjZBhr0t0d3UyPIWR7UxeKRVOaZBNDFBT1S0ZCgA5vHXQnZAJJrCVEx7WFcjgA7n4vyAnmXQsuGnIkxqHD4X5g2JcTbp5g2NFfKZBB5wfEUCv3W5d1YpAop0lOYM4FlNvif2S8ltr2bdFWvR3VCGDh9SZB6hQZDZD'

  twitter_consumer_key: "LWyr3qOUvCuwYbqOvinDH4eAT"
  twitter_consumer_secret: "X0NTRrCq1ggdkREKZSnSpBXSwZP92I3bkCxXT4L3WSL8gGKJsQ"
  twitter_access_token: "740658202132549636-oeme4uH8D07ycLY1bf68nhvUNawZdS9"
  twitter_access_token_secret: "ESqu3YUlrfGVHHjfWfmutTBbGd3j1cHzR2Fnt2zQvSQpM"

test:
  secret_key_base: 1edf9631b75f8ed9e55e7442233daab9f12ca77f5136bce9af88f081b84904d415e1fa0fc82c58a97c40c67b04607f250943d36585301015533a2fb007edc69d

  telegram_token: '234289654:AAGLp0viS8q0OXTwcPD_NYs0MUvYwp8KK_Q'
  telegram_test_chat_id: '195081'

  twilio_sid: "AC1f9a753d8c904a37dc3bbfb75d2b735c"
  twilio_token: "462fa2c260d6fb7663a75e06e1daa250"
  twilio_phone_number: "+12054172029"

  mail_server_user_name: 'e0f3c0a17413cc'
  mail_server_password: '97f6448ef8a24b'

  facebook_app_id: '1694859610767598'
  facebook_secret_key: 'a86431a4660b427582c5ce0e119c46e7'
  facebook_access_token: 'EAAYFd0ELQO4BAEpFjZBhr0t0d3UyPIWR7UxeKRVOaZBNDFBT1S0ZCgA5vHXQnZAJJrCVEx7WFcjgA7n4vyAnmXQsuGnIkxqHD4X5g2JcTbp5g2NFfKZBB5wfEUCv3W5d1YpAop0lOYM4FlNvif2S8ltr2bdFWvR3VCGDh9SZB6hQZDZD'

  twitter_consumer_key: "LWyr3qOUvCuwYbqOvinDH4eAT"
  twitter_consumer_secret: "X0NTRrCq1ggdkREKZSnSpBXSwZP92I3bkCxXT4L3WSL8gGKJsQ"
  twitter_access_token: "740658202132549636-oeme4uH8D07ycLY1bf68nhvUNawZdS9"
  twitter_access_token_secret: "ESqu3YUlrfGVHHjfWfmutTBbGd3j1cHzR2Fnt2zQvSQpM"
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  telegram_token: '234289654:AAGLp0viS8q0OXTwcPD_NYs0MUvYwp8KK_Q'
  telegram_test_chat_id: '195081'

  twilio_sid: "AC1f9a753d8c904a37dc3bbfb75d2b735c"
  twilio_token: "462fa2c260d6fb7663a75e06e1daa250"
  twilio_phone_number: "+12054172029"

  mail_server_user_name: 'e0f3c0a17413cc'
  mail_server_password: '97f6448ef8a24b'

  facebook_app_id: '1694859610767598'
  facebook_secret_key: 'a86431a4660b427582c5ce0e119c46e7'
  facebook_access_token: 'EAAYFd0ELQO4BAEpFjZBhr0t0d3UyPIWR7UxeKRVOaZBNDFBT1S0ZCgA5vHXQnZAJJrCVEx7WFcjgA7n4vyAnmXQsuGnIkxqHD4X5g2JcTbp5g2NFfKZBB5wfEUCv3W5d1YpAop0lOYM4FlNvif2S8ltr2bdFWvR3VCGDh9SZB6hQZDZD'

  twitter_consumer_key: "LWyr3qOUvCuwYbqOvinDH4eAT"
  twitter_consumer_secret: "X0NTRrCq1ggdkREKZSnSpBXSwZP92I3bkCxXT4L3WSL8gGKJsQ"
  twitter_access_token: "740658202132549636-oeme4uH8D07ycLY1bf68nhvUNawZdS9"
  twitter_access_token_secret: "ESqu3YUlrfGVHHjfWfmutTBbGd3j1cHzR2Fnt2zQvSQpM"

